// GENERATED by scripts/generate-bank-fields.mjs from the Grid OpenAPI spec.
// DO NOT EDIT BY HAND. Field facts (keys, required, patterns, enums, examples)
// are derived 1:1 from openapi/ so the demo stays accurate next to the docs.
// Regenerate:  npm run gen:bank-fields   |   Verify (CI):  npm run verify:bank-fields
//
// Every fiat external account also requires a `beneficiary` (INDIVIDUAL
// { fullName } or BUSINESS { legalName }) - added by the POST builder, not here.
/* eslint-disable */

export type BankFieldKind = 'text' | 'select';

export interface BankFieldSpec {
  key: string;
  required: boolean;
  kind: BankFieldKind;
  enum?: string[];
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  description?: string;
  example?: string;
}

export interface BankAccountSchema {
  /** Discriminator value, e.g. "USD_ACCOUNT". */
  accountType: string;
  /** ISO 4217 currency (the accountType prefix), e.g. "USD". */
  currency: string;
  /** Country-specific account fields (excludes accountType + beneficiary). */
  fields: BankFieldSpec[];
}

export const BANK_ACCOUNT_SCHEMAS: Record<string, BankAccountSchema> = {
  "AED_ACCOUNT": {
    "accountType": "AED_ACCOUNT",
    "currency": "AED",
    "fields": [
      {
        "key": "iban",
        "required": true,
        "kind": "text",
        "pattern": "^AE[0-9]{21}$",
        "minLength": 23,
        "maxLength": 23,
        "description": "UAE IBAN (23 characters, starting with AE)",
        "example": "AE070331234567890123456"
      },
      {
        "key": "swiftCode",
        "required": false,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "EBILAEAD"
      }
    ]
  },
  "BDT_ACCOUNT": {
    "accountType": "BDT_ACCOUNT",
    "currency": "BDT",
    "fields": [
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "branchCode",
        "required": false,
        "kind": "text",
        "pattern": "^[0-9]{5}$",
        "minLength": 5,
        "maxLength": 5,
        "description": "The branch code",
        "example": "11111"
      },
      {
        "key": "swiftCode",
        "required": false,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "DEUTDEFF"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "BRL_ACCOUNT": {
    "accountType": "BRL_ACCOUNT",
    "currency": "BRL",
    "fields": [
      {
        "key": "pixKey",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 77,
        "description": "The PIX key (email, phone, CPF, CNPJ, or random)",
        "example": "user@example.com"
      },
      {
        "key": "pixKeyType",
        "required": true,
        "kind": "select",
        "enum": [
          "CPF",
          "CNPJ",
          "EMAIL",
          "PHONE",
          "RANDOM"
        ],
        "description": "The type of PIX key",
        "example": "CPF"
      },
      {
        "key": "taxId",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{11,14}$",
        "minLength": 11,
        "maxLength": 14,
        "description": "The tax ID (CPF or CNPJ)",
        "example": "11111111111"
      }
    ]
  },
  "BWP_ACCOUNT": {
    "accountType": "BWP_ACCOUNT",
    "currency": "BWP",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "CAD_ACCOUNT": {
    "accountType": "CAD_ACCOUNT",
    "currency": "CAD",
    "fields": [
      {
        "key": "bankCode",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{3}$",
        "minLength": 3,
        "maxLength": 3,
        "description": "Canadian financial institution number (3 digits)",
        "example": "001"
      },
      {
        "key": "branchCode",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{5}$",
        "minLength": 5,
        "maxLength": 5,
        "description": "Transit number identifying the branch (5 digits)",
        "example": "00012"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{7,12}$",
        "minLength": 7,
        "maxLength": 12,
        "description": "Bank account number (7-12 digits)",
        "example": "1234567"
      }
    ]
  },
  "CNY_ACCOUNT": {
    "accountType": "CNY_ACCOUNT",
    "currency": "CNY",
    "fields": [
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "COP_ACCOUNT": {
    "accountType": "COP_ACCOUNT",
    "currency": "COP",
    "fields": [
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "bankAccountType",
        "required": false,
        "kind": "select",
        "enum": [
          "CHECKING",
          "SAVINGS"
        ],
        "description": "The bank account type",
        "example": "CHECKING"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "DKK_ACCOUNT": {
    "accountType": "DKK_ACCOUNT",
    "currency": "DKK",
    "fields": [
      {
        "key": "iban",
        "required": true,
        "kind": "text",
        "pattern": "^DK[0-9]{16}$",
        "minLength": 18,
        "maxLength": 18,
        "description": "Danish IBAN (18 characters, starting with DK)",
        "example": "DK5000400040116243"
      },
      {
        "key": "swiftCode",
        "required": false,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "DABADKKK"
      }
    ]
  },
  "EGP_ACCOUNT": {
    "accountType": "EGP_ACCOUNT",
    "currency": "EGP",
    "fields": [
      {
        "key": "iban",
        "required": false,
        "kind": "text",
        "pattern": "^EG[0-9]{27}$",
        "minLength": 29,
        "maxLength": 29,
        "description": "Egyptian IBAN (29 characters, starting with EG)",
        "example": "EG380019000500000000263180002"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "EUR_ACCOUNT": {
    "accountType": "EUR_ACCOUNT",
    "currency": "EUR",
    "fields": [
      {
        "key": "iban",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{2}[0-9]{2}[A-Za-z0-9]{11,30}$",
        "minLength": 15,
        "maxLength": 34,
        "description": "The IBAN of the bank account",
        "example": "DE89370400440532013000"
      },
      {
        "key": "swiftCode",
        "required": false,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "DEUTDEFF"
      }
    ]
  },
  "GBP_ACCOUNT": {
    "accountType": "GBP_ACCOUNT",
    "currency": "GBP",
    "fields": [
      {
        "key": "sortCode",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{6}$",
        "minLength": 6,
        "maxLength": 6,
        "description": "The UK sort code",
        "example": "123456"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{8}$",
        "minLength": 8,
        "maxLength": 8,
        "description": "UK bank account number (8 digits)",
        "example": "12345678"
      }
    ]
  },
  "GHS_ACCOUNT": {
    "accountType": "GHS_ACCOUNT",
    "currency": "GHS",
    "fields": [
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "GTQ_ACCOUNT": {
    "accountType": "GTQ_ACCOUNT",
    "currency": "GTQ",
    "fields": [
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "bankAccountType",
        "required": true,
        "kind": "select",
        "enum": [
          "CHECKING",
          "SAVINGS"
        ],
        "description": "The bank account type",
        "example": "CHECKING"
      }
    ]
  },
  "HKD_ACCOUNT": {
    "accountType": "HKD_ACCOUNT",
    "currency": "HKD",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Hong Kong bank account number",
        "example": "123456789012"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "HSBCHKHHHKH"
      }
    ]
  },
  "HTG_ACCOUNT": {
    "accountType": "HTG_ACCOUNT",
    "currency": "HTG",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "IDR_ACCOUNT": {
    "accountType": "IDR_ACCOUNT",
    "currency": "IDR",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Bank Central Asia"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Indonesian bank account number",
        "example": "1234567890"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "CENAIDJA"
      },
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+62[0-9]{9,12}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "Indonesian phone number for e-wallet payments",
        "example": "+6281234567890"
      }
    ]
  },
  "INR_ACCOUNT": {
    "accountType": "INR_ACCOUNT",
    "currency": "INR",
    "fields": [
      {
        "key": "vpa",
        "required": true,
        "kind": "text",
        "pattern": "^[a-zA-Z0-9.\\-_]+@[a-zA-Z0-9]+$",
        "minLength": 3,
        "maxLength": 255,
        "description": "The UPI Virtual Payment Address",
        "example": "user@upi"
      }
    ]
  },
  "JMD_ACCOUNT": {
    "accountType": "JMD_ACCOUNT",
    "currency": "JMD",
    "fields": [
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "branchCode",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{5}$",
        "minLength": 5,
        "maxLength": 5,
        "description": "The branch code",
        "example": "11111"
      },
      {
        "key": "bankAccountType",
        "required": true,
        "kind": "select",
        "enum": [
          "CHECKING",
          "SAVINGS"
        ],
        "description": "The bank account type",
        "example": "CHECKING"
      }
    ]
  },
  "KES_ACCOUNT": {
    "accountType": "KES_ACCOUNT",
    "currency": "KES",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+254[0-9]{9}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "Kenyan mobile money phone number",
        "example": "+254712345678"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "MWK_ACCOUNT": {
    "accountType": "MWK_ACCOUNT",
    "currency": "MWK",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "MXN_ACCOUNT": {
    "accountType": "MXN_ACCOUNT",
    "currency": "MXN",
    "fields": [
      {
        "key": "clabeNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{18}$",
        "minLength": 18,
        "maxLength": 18,
        "description": "The CLABE number of the bank",
        "example": "123456789012345678"
      }
    ]
  },
  "MYR_ACCOUNT": {
    "accountType": "MYR_ACCOUNT",
    "currency": "MYR",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Malaysian bank account number",
        "example": "1234567890"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "MABORUMMYYY"
      }
    ]
  },
  "NGN_ACCOUNT": {
    "accountType": "NGN_ACCOUNT",
    "currency": "NGN",
    "fields": [
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{10}$",
        "minLength": 10,
        "maxLength": 10,
        "description": "Nigerian bank account number",
        "example": "0123456789"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      }
    ]
  },
  "PHP_ACCOUNT": {
    "accountType": "PHP_ACCOUNT",
    "currency": "PHP",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "Name of the beneficiary's bank",
        "example": "BDO Unibank"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{8,16}$",
        "minLength": 8,
        "maxLength": 16,
        "description": "Bank account number",
        "example": "001234567890"
      }
    ]
  },
  "PKR_ACCOUNT": {
    "accountType": "PKR_ACCOUNT",
    "currency": "PKR",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "iban",
        "required": false,
        "kind": "text",
        "pattern": "^PK[0-9]{2}[A-Z]{4}[0-9]{16}$",
        "minLength": 24,
        "maxLength": 24,
        "description": "Pakistani IBAN (24 characters, starting with PK)",
        "example": "PK36SCBL0000001123456702"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      }
    ]
  },
  "RWF_ACCOUNT": {
    "accountType": "RWF_ACCOUNT",
    "currency": "RWF",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+250[0-9]{9}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "Rwandan mobile money phone number",
        "example": "+250781234567"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "SGD_ACCOUNT": {
    "accountType": "SGD_ACCOUNT",
    "currency": "SGD",
    "fields": [
      {
        "key": "bankName",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "Name of the beneficiary's bank. When omitted, resolved from swiftCode via the payout partner bank directory at account creation.",
        "example": "DBS Bank Ltd"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Bank account number",
        "example": "0123456789"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "DBSSSGSG"
      }
    ]
  },
  "SLV_ACCOUNT": {
    "accountType": "SLV_ACCOUNT",
    "currency": "SLV",
    "fields": [
      {
        "key": "bankName",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank (BANK_TRANSFER only)",
        "example": "Banco Cuscatlan"
      },
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank (BANK_TRANSFER only)",
        "example": "0123456789"
      },
      {
        "key": "bankAccountType",
        "required": false,
        "kind": "select",
        "enum": [
          "CHECKING",
          "SAVINGS"
        ],
        "description": "The bank account type (BANK_TRANSFER only)",
        "example": "CHECKING"
      },
      {
        "key": "phoneNumber",
        "required": false,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format (MOBILE_MONEY only — e.g. Tigo Money)",
        "example": "+50312345678"
      }
    ]
  },
  "SWIFT_ACCOUNT": {
    "accountType": "SWIFT_ACCOUNT",
    "currency": "SWIFT",
    "fields": [
      {
        "key": "country",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{2}$",
        "minLength": 2,
        "maxLength": 2,
        "description": "The ISO 3166-1 alpha-2 country code of the bank account",
        "example": "NG"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "DEUTDEFF"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Deutsche Bank"
      },
      {
        "key": "accountNumber",
        "required": false,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The bank account number. Required for most corridors. Use iban instead for IBAN-only corridors (e.g. BR, GB).",
        "example": "1234567890"
      },
      {
        "key": "iban",
        "required": false,
        "kind": "text",
        "pattern": "^[A-Z]{2}[0-9]{2}[A-Za-z0-9]{11,30}$",
        "minLength": 15,
        "maxLength": 34,
        "description": "The IBAN of the bank account. Required for IBAN-only corridors (e.g. BR, GB). Use accountNumber for all other corridors.",
        "example": "GB29NWBK60161331926819"
      }
    ]
  },
  "THB_ACCOUNT": {
    "accountType": "THB_ACCOUNT",
    "currency": "THB",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Thai bank account number",
        "example": "1234567890"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "BKKBTHBK"
      }
    ]
  },
  "TZS_ACCOUNT": {
    "accountType": "TZS_ACCOUNT",
    "currency": "TZS",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+255[0-9]{9}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "Tanzanian mobile money phone number",
        "example": "+255712345678"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "UGX_ACCOUNT": {
    "accountType": "UGX_ACCOUNT",
    "currency": "UGX",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  },
  "USD_ACCOUNT": {
    "accountType": "USD_ACCOUNT",
    "currency": "USD",
    "fields": [
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "The account number of the bank",
        "example": "1234567890"
      },
      {
        "key": "routingNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{9}$",
        "minLength": 9,
        "maxLength": 9,
        "description": "The ABA routing number",
        "example": "021000021"
      }
    ]
  },
  "VND_ACCOUNT": {
    "accountType": "VND_ACCOUNT",
    "currency": "VND",
    "fields": [
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      },
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 34,
        "description": "Vietnamese bank account number",
        "example": "1234567890"
      },
      {
        "key": "swiftCode",
        "required": true,
        "kind": "text",
        "pattern": "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
        "minLength": 8,
        "maxLength": 11,
        "description": "The SWIFT/BIC code of the bank",
        "example": "BFTVVNVX"
      }
    ]
  },
  "XAF_ACCOUNT": {
    "accountType": "XAF_ACCOUNT",
    "currency": "XAF",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      },
      {
        "key": "region",
        "required": true,
        "kind": "select",
        "enum": [
          "CM",
          "CG"
        ],
        "pattern": "^[A-Z]{2}$",
        "minLength": 2,
        "maxLength": 2,
        "description": "Country code within the Central African CFA franc zone",
        "example": "CM"
      }
    ]
  },
  "XOF_ACCOUNT": {
    "accountType": "XOF_ACCOUNT",
    "currency": "XOF",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+[0-9]{6,14}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "The phone number in international format",
        "example": "+1234567890"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      },
      {
        "key": "region",
        "required": true,
        "kind": "select",
        "enum": [
          "BJ",
          "CI",
          "SN",
          "TG"
        ],
        "pattern": "^[A-Z]{2}$",
        "minLength": 2,
        "maxLength": 2,
        "description": "Country code within the West African CFA franc zone",
        "example": "BJ"
      }
    ]
  },
  "ZAR_ACCOUNT": {
    "accountType": "ZAR_ACCOUNT",
    "currency": "ZAR",
    "fields": [
      {
        "key": "accountNumber",
        "required": true,
        "kind": "text",
        "pattern": "^[0-9]{9,13}$",
        "minLength": 9,
        "maxLength": 13,
        "description": "South African bank account number",
        "example": "1234567890"
      },
      {
        "key": "bankName",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The name of the bank",
        "example": "Example Bank"
      }
    ]
  },
  "ZMW_ACCOUNT": {
    "accountType": "ZMW_ACCOUNT",
    "currency": "ZMW",
    "fields": [
      {
        "key": "phoneNumber",
        "required": true,
        "kind": "text",
        "pattern": "^\\+260[0-9]{9}$",
        "minLength": 7,
        "maxLength": 15,
        "description": "Zambian mobile money phone number",
        "example": "+260971234567"
      },
      {
        "key": "provider",
        "required": true,
        "kind": "text",
        "minLength": 1,
        "maxLength": 255,
        "description": "The mobile money provider name",
        "example": "Example Provider"
      }
    ]
  }
};
